sudo: required

language: go

go:
  - go1.7
  - go1.8
  - go1.9
  - tip

install:
  - go get -u github.com/dustin/go-humanize
  - go get -u github.com/fzipp/gocyclo
  - go get -u github.com/golang/geo/s1
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/golang/protobuf/proto
  - go get -u github.com/stretchr/testify/assert
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u gopkg.in/cheggaaa/pb.v1

script:
  - go install
  - test -z "$(goimports -l -w $(go list -f {{.Dir}}/*.go ./...) | tee /dev/stderr)"
  - golint ./...
  - gocyclo -over 15 .
  - go tool vet .
  - go test -v -race ./...
  - ./build/codecov.sh
  - PBF_PROTO_BUFFER_SIZE=33554432 PBF_NCPU=4 go test -bench=. -benchtime=10s

after_success:
  - bash <(curl -s https://codecov.io/bash)
