sudo: required

language: go

go:
  - go1.7
  - go1.8
  - go1.9
  - tip

install:
  - go get -u github.com/golang/lint/golint
  - go get -u golang.org/x/tools/cmd/goimports
  - go get -u github.com/golang/protobuf/proto
  - go get -u github.com/stretchr/testify/assert
  - go get -u gopkg.in/cheggaaa/pb.v1

script:
  - go install
  - test -z "$(goimports -l -d $(go list -f {{.Dir}}/*.go ./...) | tee /dev/stderr)"
  - test -z "$(golint ./... | tee /dev/stderr)"
  - go tool vet .
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
