sudo: required

language: go

go:
  - go1.7
  - go1.8
  - go1.9
  - tip

install:
  - curl https://glide.sh/get | sh
  - glide install
  - go get -u github.com/golang/lint/golint
  - go get -u github.com/fzipp/gocyclo
  - ./build/vanity.sh

script:
  - go install
  - test -z "$(goimports -l -w $(go list -f {{.Dir}}/*.go ./...  | grep -v /vendor/) | tee /dev/stderr)"
  - golint $(go list -f {{.Dir}} ./... | grep -v /vendor/)
  - gocyclo -over 15 $(go list -f {{.Dir}}/*.go ./... | grep -v /vendor/)
  - go tool vet $(go list -f {{.Dir}}/*.go ./... | grep -v /vendor/)
  - ./build/codecov.sh
  - PBF_PROTO_BUFFER_SIZE=33554432 PBF_NCPU=4 go test -bench=. -benchtime=10s

after_success:
  - bash <(curl -s https://codecov.io/bash)
